dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shamsi_date: ^1.0.3
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
